### ISSUE TITLE
With "non-production runs to a development schema" enabled, compiled query incorrectly references prod schema

### ISSUE THREAD

**Issue by lewish** [dataform-co/dataform-web-tracking#144]
Steps to reproduce:

Enter development mode
Switch on "non-production runs to a development schema"
Open a query
Check "compiled query"

Expected result: references the branch names schema
Actual results: references the production schema

also effect validation, preview results

---
Moved from dataform-co/dataform-co#899
/cc @dwl285

**Comment by BenBirt** [comment]
fixed!
