### ISSUE TITLE
Git branch errors after migrating to GitHub: object not found - no match for id

### ISSUE THREAD

**Issue by lewish** [dataform-co/dataform-web-tracking#146]
After migrating a project to GitHub, pushing one of the branches and merging to master (via GitHub) then opening another branch - an error along the following lines shows:

```
object not found - no match for id (...)
```

**Comment by lewish** [comment]
This is actually mostly harmess, and can be fixed with a git pull, however we don't show the git pull button when this exception get's thrown.
Alternative workaround is to just create a new clean branch

**Comment by lewish** [comment]
Suggested fix:

In the case of exceptions thrown during `git status` calls when getting the branch info, we should still show the "Pull from ..." button in the top toolbar.

**Comment by BenBirt** [comment]
I can't seem to reproduce this. @lewish are there other steps than those listed in the first comment?

Just thinking this through, I'm assuming this error is complaining that a commit is missing from either our the `dataform_head` branch on the `head` repo or maybe the `dataform_<branch>` branch on the github repo?

I've tried creating commits on two separate branches on dataform, and various combinations of pushing them to github / merging them on github, but I can't get this error to trigger...

**Comment by BenBirt** [comment]
Closing until we can reproduce. (hopefully this won't happen again as a result of recent git integration fixes.)
