### ISSUE TITLE
Transient schedule failures due to missing temporarily file

### ISSUE THREAD

**Issue by lewish** [dataform-co/dataform-web-tracking#153]
```
 Unable to compile project: ENOENT: no such file or directory, open '/tmp/dataform/...'
```
This is transient, I believe it's mostly likely due to two project compilations kicking off at exactly the same time. We can re-evaluate how we pass back compilation results here, or implement a global lock on project + branch.

**Comment by BenBirt** [comment]
I propose instead writing to a randomly generated directory in `/tmp` (and then deleting that directory post-compilation), that way we can be lockless.
