### ISSUE TITLE
Cant specify a BigQuery dataset location outside of US/EU

### ISSUE THREAD

**Issue by lewish** [dataform-co/dataform-web-tracking#158]
This needs to be changed in both the CLI and Dataform Web.

Full list of locations is available here: https://cloud.google.com/bigquery/docs/locations

Let's change the US/EU button switch to a drop-down with US and EU first, and then the others after. Ideally we would clearly show the difference between these being multi-regional and regional locations.

**Comment by BenBirt** [comment]
@ferparra this fix will go out in the next release of the webapp, should be out within a day or so.
