### ISSUE TITLE
SQL code editor scrolling not working as expected on firefox

### ISSUE THREAD

**Issue by dwl285** [dataform-co/dataform-web-tracking#160]
With mouse hovering within the editor pane, rather than scrolling only the editor pane, the entire page scrolls

See intercom conversation for more details:
https://app.intercom.io/a/apps/nnz2jx08/inbox/inbox/conversation/23254447805#part_id=comment-23254447805-3562652816

**Comment by faiyaz26** [comment]
just checked, can't reproduce. @BenBirt @dwl285 I believe its fixed after some change from George
