### ISSUE TITLE
Give users a way to autocomplete ref() with actions that exist within their compiled graph

### ISSUE THREAD

**Issue by dwl285** [dataform-co/dataform-web-tracking#163]
Some shorthand for pulling up an autocomplete for all things you could possible ref(), that then fills in the ${ref()} syntax around the action name you've chosen

For example if you type "ref:" an autocomplete menu pops open

**Comment by BenBirt** [comment]
After discussion, let's make a new key-combo (cmd+shift+r or something) that pops open a dropdown (or similar) containing all action names (probably fully qualified, i.e. `schema.name`). Hitting enter then pops text into the editor, `${ref({schema: "schema", name: "name"})}`.

**Comment by lewish** [comment]
Moved to canny

**Comment by lewish** [comment]
https://dataform.canny.io/feature-requests/p/add-autocompletion-for-from-statements-in-the-editor
