### ISSUE TITLE
Add compilation status indicator to the top nav bar

### ISSUE THREAD

**Issue by lewish** [dataform-co/dataform-web-tracking#164]
As discussed, it would be useful to have a way to see project level compilation errors while editing files.

Proposal:
- Add a compilation status indicator tag or icon to the top bar, to the right of the git controls
- Show the project status warnings that show on the overview page in a popover when clicking on the icon

Optionally, if tight on space, consider moving either the focus mode controls or the documentation link into the file header bar instead.

---
Moved from dataform-co/dataform-co#1350
/cc @lewish

**Comment by lewish** [comment]
Additionally, we should add a warning popup if the user attempts to commit or push if there are compilation errors.

**Comment by dwl285** [comment]
Design: add a tag on the navbar:
![image](https://user-images.githubusercontent.com/2012230/64365636-80c3a080-d00c-11e9-9501-799f0073b2a5.png)

That opens a popover 
![image](https://user-images.githubusercontent.com/2012230/64365912-06dfe700-d00d-11e9-9daf-3c2de841bd79.png)
(For illustration purposes only, let's use the same style as the card)

**Comment by GJMcGowan** [comment]
@dwl285 I didn't see this ticket when making this change for the status card on the overview page. 

Currently the compilation and validation errors take you to the overview page, where the status card can tell you more - is that good, or should we do the popover?

**Comment by lewish** [comment]
Nah you good
