### ISSUE TITLE
"Include dependencies" option should display to the user what extra actions will be included

### ISSUE THREAD

**Issue by BenBirt** [dataform-co/dataform-web-tracking#167]
---
Moved from dataform-co/dataform-co#1407
/cc @BenBirt

**Comment by Jagjit-Thind** [comment]
Even if the "Include dependencies" option is not selected and the user explicitly selects many actions (which includes upstream dependent ones), it is very useful to see what will happen when starting a new run, also in the run history. So you can see what actions will / got executed in what order.

**Comment by lewish** [comment]
Tracking here: https://dataform.canny.io/feature-requests/p/show-what-actions-will-be-run-when-dependencies-are-included
