### ISSUE TITLE
We should allow users to run .sql and .sqlx files that are stored outside of the definitions folder

### ISSUE THREAD

**Issue by dwl285** [dataform-co/dataform-web-tracking#168]
Some of our users have folders at the top level of their repo to store queries that they'd like to version control, but that are not involved with the dataform model. We should let people run .sql/.sqlx files (add an "Execute Query" button to RSH).

This would only work if there was no config {} or js{} block

**Comment by BenBirt** [comment]
I wonder if we can make this feature a bit more nice/clean. It sounds like some users want to store simple queries that are more useful snippets than anything else. We could let them do just that: store named SQL snippets, not in files (but instead in the DB). The only big consideration is whether or not version control is important on these queries.

**Comment by lewish** [comment]
Moved to canny
