### ISSUE TITLE
Templates should prompt the user before overwriting the contents of the file

### ISSUE THREAD

**Issue by dwl285** [dataform-co/dataform-web-tracking#169]
If the file is not empty, first show the user a modal: This will overwrite the contents of the current file. (OK/Cancel).

**Comment by BenBirt** [comment]
@dwl285 did this actually overwrite somebody's real code? The template choice UI should only be showing up for empty files / files that themselves contain literal copies of some template, if it's showing up in other circumstances then that's a bug.

**Comment by BenBirt** [comment]
closing in favour of https://github.com/dataform-co/dataform-co/issues/1538
