### ISSUE TITLE
SQL validation errors on Redshift don't have line numbers

### ISSUE THREAD

**Issue by dwl285** [dataform-co/dataform-web-tracking#170]
We don't currently show line numbers with query validation errors for Redshift. The redshift console shows position (which we don't), so it looks like we are potentially missing part of the error message in what we display.

Example Query:
```
select
1 ast test
```
Dataform error message:
`error: syntax error at or near "test"`
Redshift console error message:
`[Amazon](500310) Invalid operation: syntax error at or near "test" Position: 14;`

**Comment by BenBirt** [comment]
from @lewish in the other issue:

Redshift seems to split errors into the top level error and then additional details. These additional details don't get propagated anywhere, and leaves some high level messages such as the following that are hard to debug:
```
Assert
deadlock detected
```

Additionally, it appears line/column number information is available, but we don't show it.

We should look at all the fields that redshift errors might have and make sure they get added to the overall error message.
