### ISSUE TITLE
link dependencies on RHS of file editor to the file in which they are defined

### ISSUE THREAD

**Issue by dwl285** [dataform-co/dataform-web-tracking#186]
![image](https://user-images.githubusercontent.com/4967152/65249902-a2348a00-daec-11e9-8a1d-2e7d9b85a4f8.png)

**Comment by dwl285** [comment]
Requested by Luiz @ Liv Up

**Comment by GJMcGowan** [comment]
This was fixed in a previous PR: https://github.com/dataform-co/dataform-co/pull/1928
