### ISSUE TITLE
Preview query doesn't work with Redshift Spectrum when selecting a STRUCT

### ISSUE THREAD

**Issue by dwl285** [dataform-co/dataform-web-tracking#189]
Preview results fails when selecting a struct field from a spectrum table. This is because
a) spectrum doesn't allow structs to be within a subquery
b) we wrap queries in a SELECT * FROM (...) limit 1000 before sending the preview results query to redshift

Example query:
```
SELECT
  struct.field
from
  spectrum.table
limit 10
```

**Comment by dwl285** [comment]
cc @maxcountryman

**Comment by BenBirt** [comment]
fixed
