### ISSUE TITLE
"Push to branch" button takes a few seconds to disappear on production screen

### ISSUE THREAD

**Issue by dwl285** [dataform-co/dataform-web-tracking#199]
Steps to recreate:
make changes in dev
commit them
push to git
open the pull request and resolve
come back to DF and refresh the page
do the pull from master
then after that pull has resolved click on production

![image](https://user-images.githubusercontent.com/4967152/67219005-39a83800-f41f-11e9-9105-2fe68783677a.png)

**Comment by dwl285** [comment]
From Mike Lee on whether it disappears after a while:

> sometimes it hangs, sometimes it stays
> I've had two stayers and two goers so far today

**Comment by BenBirt** [comment]
@GJMcGowan do you know if this is fixed now?

**Comment by GJMcGowan** [comment]
Fixedish. I did these steps on my local machine and did not experience any hanging around or weirdness like above.

I do see the wrong text while the git status is loading (should be telling me to push) but I think that is a different issue.

![Screenshot 2019-10-28 at 12.08.44.png](https://codetreeusercontent.s3.amazonaws.com/uploads/bc1b835b-7f2d-45c0-9d24-61af2e4a73f8/Screenshot+2019-10-28+at+12.08.44.png)

**Comment by GJMcGowan** [comment]
I made more changes to remove this today, I'm going to close.
