### ISSUE TITLE
"Open pull request on github" opens a PR page comparing master to master

### ISSUE THREAD

**Issue by dwl285** [dataform-co/dataform-web-tracking#206]
e.g. this in the link created in the dataform-data project on the `test_drop_table` branch

https://github.com/dataform-co/dataform-data/compare/master...master

![image](https://user-images.githubusercontent.com/4967152/68396085-d92c3100-0168-11ea-9f8e-46e447305ed3.png)

**Comment by GJMcGowan** [comment]
For certain branches, this will also show "push to master" when we should say "push to {branchName}"

This doesn't affect the actual push though - it's just a UI issue.

Should be "Push to Georgio"
<img width="485" alt="Screenshot 2019-11-08 at 11 16 18" src="https://user-images.githubusercontent.com/5724925/68473091-f7059e80-0219-11ea-813c-1a15c4449b4e.png">

Clicking "Push to master" still means you have to raise a PR though:
<img width="602" alt="Screenshot 2019-11-08 at 11 21 57" src="https://user-images.githubusercontent.com/5724925/68473137-0dabf580-021a-11ea-8791-9476be41b274.png">
