### ISSUE TITLE
Data Catalog: Matching field descriptions against fields in the warehouse should not be case sensitive

### ISSUE THREAD

**Issue by dwl285** [dataform-co/dataform-web-tracking#208]
This is particularly problematic in Snowflake, where all field names are automatically capitalised when datasets are published in the warehouse.

**Comment by GJMcGowan** [comment]
In the definition we might have a `revenue` column and have a description attached to it. But the catalog will report the column as `REVENUE` and not attach the description. So we should make these case-insensitive.
