### ISSUE TITLE
Stop directing the user to deleted branches

### ISSUE THREAD

**Issue by lewish** [dataform-co/dataform-web-tracking#211]
The project list page directs users to the last branch they were on, even if it no longer exists - let's change that logic to only direct them there if the branch still exists.

IMO we should also redirect users to the production branch if they try to go directly to a deleted branch.

---
Moved from dataform-co/dataform-co#1938
/cc @BenBirt

**Comment by Ekrekr** [comment]
There is already a redirect in place for a branch that doesn't exist (or is deleted) to the user default, e.g. `...40720/b/asd` is redirected to `...40720/overview`. This redirect does not happen for child routes, e.g. `...40720/b/asd/overview` is not redirected.

This is likely to do with the `<IndexRedirect/>` for branches, but I do not know enough about react routing to fix.
