### ISSUE TITLE
Intermittent login issues

### ISSUE THREAD

**Issue by GJMcGowan** [dataform-co/dataform-web-tracking#212]
User is experiencing two issues:
* App is logging them out quite quickly (several times a day).
* When trying to log back in sometimes they will not be able to, and will see the following message:
![](https://downloads.intercomcdn.com/i/o/177358341/720f58e1d1a42df47cc4dcd4/Screenshot+2020-01-16+at+12.09.34.png)

(Console error is "state does not match") thrown by Auth0.

User tried the following resolutions:
* Clearing URL
* Clearing cookies/hard refresh
* Ensuring third party cookies are enabled.

The issue went away after they retried a few minutes (or waited a few minutes).

**Comment by dallerup** [comment]
I think maybe it can be trigger by having the browser be inactive for some time. An example I saw this going to lunch and when I came back I had to login and got the error above.
