### ISSUE TITLE
Permission denied on Redshift databases causes UI issues

### ISSUE THREAD

**Issue by GJMcGowan** [dataform-co/dataform-web-tracking#213]
When user gets a Permission Denied error on a redshift database, we get an unhandled promise rejection. The run will be put into our database without a runResult on it. This causes the server to break, which bubbles up to the UI in toasters all over the place.

We should handle the promise rejection properly, and not put weird stuff in our database.

[Log of initial error](https://console.cloud.google.com/logs/viewer?project=tada-analytics&minLogLevel=0&expandAll=false&timestamp=2020-01-17T16%3A31%3A20.602000000Z&customFacets&limitCustomFacetWidth=true&dateRangeStart=2020-01-17T15%3A31%3A12.760Z&interval=PT1H&scrollTimestamp=2020-01-17T16%3A24%3A40.549999952Z&advancedFilter=resource.type%3D%22container%22%0Aresource.labels.project_id%3D%22tada-analytics%22%0Aresource.labels.cluster_name%3D%22dataform-cluster-eu-west1%22%0Aresource.labels.namespace_id%3D%22app-prod%22%0Atimestamp%3D%222020-01-17T16%3A00%3A11.243000030Z%22%0AinsertId%3D%22........0BLewTgnnU48Zf6tS6cnJRW6%22&dateRangeUnbound=forwardInTime)
[Log of promise rejection error](https://console.cloud.google.com/logs/viewer?project=tada-analytics&minLogLevel=0&expandAll=false&timestamp=2020-01-17T16%3A31%3A20.602000000Z&customFacets&limitCustomFacetWidth=true&dateRangeStart=2020-01-17T15%3A31%3A12.760Z&interval=PT1H&scrollTimestamp=2020-01-17T16%3A24%3A40.549999952Z&advancedFilter=resource.type%3D%22container%22%0Aresource.labels.project_id%3D%22tada-analytics%22%0Aresource.labels.cluster_name%3D%22dataform-cluster-eu-west1%22%0Aresource.labels.namespace_id%3D%22app-prod%22%0Atimestamp%3D%222020-01-17T16%3A00%3A11.256000041Z%22%0AinsertId%3D%22........0BPewTgnnU48Zf6tS6cnJRW6%22&dateRangeUnbound=forwardInTime)
[Final error thrown whenever RunGet is called](https://console.cloud.google.com/logs/viewer?project=tada-analytics&minLogLevel=0&expandAll=false&timestamp=2020-01-17T16%3A31%3A20.602000000Z&customFacets&limitCustomFacetWidth=true&dateRangeStart=2020-01-17T15%3A31%3A12.760Z&interval=PT1H&scrollTimestamp=2020-01-17T16%3A24%3A40.549999952Z&advancedFilter=resource.type%3D%22container%22%0Aresource.labels.namespace_id%3D%22app-prod%22%0Aresource.labels.project_id%3D%22tada-analytics%22%0Aresource.labels.cluster_name%3D%22dataform-cluster-eu-west1%22%0Atimestamp%3D%222020-01-17T16%3A00%3A24.065999984Z%22%0AinsertId%3D%22........BarWkr4l7u_1edCAk1YQLFcH%22&dateRangeUnbound=forwardInTime)

**Comment by BenBirt** [comment]
Note: we now handle the 'bad' data correctly, the thing that needs fixing here is the unhandled promise rejection.
