### ISSUE TITLE
Enabling the "add suffix to output schema names" option on a run results in a run with 0 actions

### ISSUE THREAD

**Issue by dwl285** [dataform-co/dataform-web-tracking#215]
Steps to reproduce:

Open a sqlx table file
- click `Publish table`
- open advanced options
- toggle `add suffix to output schema names` on
- click `Run now`

Expected result:
- run with this action starts

Actual result:
- run with 0 actions starts

**Comment by gauravthanvi** [comment]
Hey Team, any updates on this issues?

**Comment by GJMcGowan** [comment]
Hi @gauravthanvi - we're going to release something which we hope will fix the issue today.

**Comment by GJMcGowan** [comment]
This is now released and should work on production.
