### ISSUE TITLE
hyphens in branch names are not supported by "publish table/view" option with dev schemas on

### ISSUE THREAD

**Issue by dwl285** [dataform-co/dataform-web-tracking#216]
Steps to reproduce:
- Create a branch with a hyphen (e.g. `test-branch`)
- turn on isolated dev schemas
- run "publish table/view" from web IDE

expected result:
- a run is created including this action

actual result:
- a run is created with 0 actions

Note: "Start new run" does work (it automatically converts the "-" to an "_"

**Comment by BenBirt** [comment]
Likely related to https://github.com/dataform-co/dataform-co/issues/6874
