### ISSUE TITLE
No way to see incremental table code when using when() statements

### ISSUE THREAD

**Issue by lewish** [dataform-co/dataform-web-tracking#217]
With the new incremental when() statements, there is no way to view the incremental version of the query in the Web UI.

Ideally we should show both the incremental and non-incremental versions. We should do this for pre/post operations too.

**Comment by Ekrekr** [comment]
Fixed in https://github.com/dataform-co/dataform-co/pull/4293

**Comment by BenBirt** [comment]
WORK LEFT: make it possible to view incremental versions of pre/post ops.
