### ISSUE TITLE
Two schedules shouldn't be allowed to run at the same time

### ISSUE THREAD

**Issue by dwl285** [dataform-co/dataform-web-tracking#220]
- If a manually triggered schedule is running, don't start any scheduled schedules
- if a scheduled schedule is running, don't allow users to manually trigger a schedule

Note: this behaviour should be per-environment

**Comment by BenBirt** [comment]
Note: we suspect this was a regression caused by turning on environments; i.e. the manually-triggered schedule does not have an environment set.

**Comment by BenBirt** [comment]
Leaving some notes here about discussed solutions:
- We should start marking all runs, regardless of how they are triggered (whether running a schedule, or the Run button), with an environment. The current proposal is that we mark the environment as `branch: <branch name>`, where `branch name` may be `master`, if the user isn't on a development branch.
- We should change `Production` to `master` to more clearly message that the code being looked at is on the Git `master` branch, but *is not necessarily* the user's `Production` environment
- We should give the user the ability to trigger manual runs of a schedule from within an environment. There are two options here: (1) When on the `master` branch, the user should have some dropdown next to `Manually run this schedule` allowing them to specify which environment should run, or (2) we should turn the `Production/master` selector at the top of the app to a dropdown to allow the user to explore their code, and manually trigger schedules, *within that environment*. (1) is easier to implement but not as featureful as (2). We should probably start with (1) and then get to (2) later.

**Comment by BenBirt** [comment]
"Manual run" schedules (when triggered from environments.json) now have an `environmentName` attached.
