### ISSUE TITLE
Wrong hover text on right-hand sidebar toggle button

### ISSUE THREAD

**Issue by kadu-vido** [dataform-co/dataform-web-tracking#224]
The right-hand sidebar toggle button shows "Toggle footer" on the hover text:

If you have trouble reproducing, the dataform page I'm looking at has no footer, and I'm running brave browser v1.4.96 on ubuntu 18.04 (64bit)

![image](https://user-images.githubusercontent.com/5318737/77008987-ed1d4600-6945-11ea-9e67-6eb194ae6da1.png)

**Comment by GJMcGowan** [comment]
Thanks for letting us know! This should be resolved now.
