### ISSUE TITLE
"Deployment finished" toasters re-triggered when opening a project

### ISSUE THREAD

**Issue by dwl285** [dataform-co/dataform-web-tracking#228]
Steps to reproduce:
- Open a project
- Kick off a run
- Wait for "deployment finished" toaster to appear
- open projects list
- reopen same project

Expected result:
- deployment finished toaster is not shown on project list page
- When you reopen the project, either one or zero toasters are showing (probably zero?)

Actual result:
- toaster is shown on project list page
- toaster is triggered a second time when you reopen to project

There are some other strange behaviours relating to deployment finished toaster that are presumably related, read this intercom chat for more info: https://app.intercom.com/a/apps/nnz2jx08/inbox/inbox/3262041/conversations/26440266998

**Comment by lewish** [comment]
I think this should be fixed now!
