### ISSUE TITLE
"1 run in progress" tag links to previously completed run

### ISSUE THREAD

**Issue by dwl285** [dataform-co/dataform-web-tracking#229]
Steps to reproduce:
- Start a new run
- Wait for it to finish
- Start another run
- Wait for "1 run in progress" tag to appear in top RHS
- Click on "1 run in progress" tag

Expected result:
- Opens the run that is currently in progress

Actual result:
- Open the previous run

**Comment by Ekrekr** [comment]
Can't reproduce, seems to have been fixed
