### ISSUE TITLE
Preview results for large datasets leads to "no healthy upstream" error

### ISSUE THREAD

**Issue by G2H** [dataform-co/dataform-web-tracking#235]
For example, click "preview results" on the `sessions_full.sqlx` table on our internal project.

![image](https://user-images.githubusercontent.com/4967152/81694165-e9470500-9458-11ea-96d3-d23280aed590.png)

**Comment by BenBirt** [comment]
If this is happening, it suggests that some queries result in rows that are so large that the job-service OOMs (even though we limit the number of rows returned).

I wasn't able to reproduce this error specifically, though I was able to reproduce "Preview results" failing with some other error (timeout?). Regardless, we should be limiting the total MB size that we allow to be returned to our servers.
