### ISSUE TITLE
Run logs page should automatically refresh to show updated status of a run when it completes

### ISSUE THREAD

**Issue by dwl285** [dataform-co/dataform-web-tracking#237]
When a run finishes, `status`, `actions` and `duration` should automatically update without requiring a page reload.

**Comment by dwl285** [comment]
I just checked and this issue still exists. The "completed successfully" toaster appears, and the token in the navbar appears, but the status in the run list doesn't update.

![image](https://user-images.githubusercontent.com/4967152/81564222-53937300-938f-11ea-8eb1-986b94d86a09.png)

**Comment by BenBirt** [comment]
Cannot reproduce
