### ISSUE TITLE
[Tracking] Snowflake runs failing during "build" phase with `ECONNRESET` or `ESOCKETTIMEDOUT`

### ISSUE THREAD

**Issue by lewish** [dataform-co/dataform-web-tracking#244]
Depends on dataform-co/dataform-co#6939

**Comment by BenBirt** [comment]
I'm closing this out, for now.

We worked extensively with the Snowflake team and know that (at least in part) OCSP status checking is a cause of this behaviour. For now, that's switched off in Dataform. Snowflake have work to do internally to improve their nodejs client library.

**Comment by BenBirt** [comment]
Snowflake's ticket references are:
- SNOW-174019 (The issue initially reported)
- SNOW-202899 (NodeJS Driver improvement for high concurrency)
