### ISSUE TITLE
Query validation incorrectly showing error for Redshift COPY commands

### ISSUE THREAD

**Issue by dwl285** [dataform-co/dataform-web-tracking#279]
Example:
```
copy catdemo
from 's3://awssampledbuswest2/tickit/category_pipe.txt'
iam_role 'arn:aws:iam::<aws-account-id>:role/<role-name>'
region 'us-west-2';
```

Validation error should be: `ERROR: Cannot COPY into nonexistent table catdemo`
Actual validation error: `Error: Error executing redshift query: syntax error at or near "copy"play`

**Comment by BenBirt** [comment]
I don't think fixing this is feasible.

Validation entails `explain`ing the query. If you `explain` that query in the Redshift console, you get `ERROR: syntax error at or near "copy" Position: 9` (which shows up in Dataform as `Error: Error executing redshift query: syntax error at or near "copy"`).

It's only through actually *running* the query that you get the `ERROR: Cannot COPY into nonexistent table catdemo` error.
