### ISSUE TITLE
No clear way to create a new folder

### ISSUE THREAD

**Issue by lewish** [dataform-co/dataform-web-tracking#52]
Currently only way to create a folder is to put a file in the folder by giving it a name like:

`models/my_new_folder/new_model.sql`

This is confusing and not obvious, should have an option to create folders themselves.

**Comment by dwl285** [comment]
If there is a way to do this that would enable changing the folder name for many files at once, that'd be excellent. If not, then when this issue gets closed, we should create another issue for being able to change the folder name

**Comment by dwl285** [comment]
potentially needs design work @G2H

**Comment by G2H** [comment]
![image](https://user-images.githubusercontent.com/2012230/64244205-89c74b80-cf00-11e9-825f-644e15791b62.png)

**Comment by BenBirt** [comment]
fixed!
