### ISSUE TITLE
More intuitive model order in deploy select - also maybe a search filter?

### ISSUE THREAD

**Issue by chrisgoddard** [dataform-co/dataform-web-tracking#60]
When you want to edit the tables you wish to deploy, it's unclear what order the models are in - it's not alphabetical.

<img width="482" alt="screen shot 2018-08-01 at 11 11 18 am" src="https://user-images.githubusercontent.com/4922472/43540178-d6dedbe6-957b-11e8-9e8f-3e045ed75e5f.png">

Having alphabetical ordering would be better to navigate (especially when you have a lot of them!) - but it would also be helpful to have a search filter - similar to how BigQuery now lets you search through datasets and tables with a text filter:

<img width="509" alt="screen shot 2018-08-01 at 11 13 59 am" src="https://user-images.githubusercontent.com/4922472/43540244-0b06e6e8-957c-11e8-8cd0-c3d014ee2f93.png">

**Comment by G2H** [comment]
Great points! The model names are now ordered alphabetically. We should be able to add a text filter next week.
